### ISSUE TITLE
How do I make my YouTube data cumulative?

### ISSUE THREAD

**Issue by PF94** [carykh/AbacabaTutorialDrawer#1]
I've wanted to do an Abacaba-styled video with this tool. But then I tried to export my YouTube video's view count and it looks like this.
![image](https://user-images.githubusercontent.com/45898787/103468979-f472dc00-4d2c-11eb-9281-4e981475c4b2.png)
If I put that data in the Abacaba Graph Drawer tool. Then it's going to fluctuate.

I asked this on the part 1 video's comment section. I only got a "There's no way" reply, and there was radio-slience after.

The guy claimed that post-late-2018 videos counts the total views over time, but I exported a post-late-2018 video and it was still the same fluctuating mess.

Here's the problem, I have uploaded a total of 450-525 videos over a period of almost 7 years. I cannot count manually the total views for 450-525 videos. I did try to do an "animated graph video" of my videos earlier last year, however, because of the "all videos' views are counted separately each day" issue, i ended making my data incomplete and smooth because I found the process too tedious. 

Before I wrote this, I looked on YouTube and Google if there was any way of counting the videos' total views for each day, but my results were only "How YouTube counts views" and shoddy attempts at trying to advertise VidIQ's paid features.

So, my question is, is there any way of counting the total view of a YouTube video for each day? I don't care if this requires a retro version of Python along with Ubuntu 14.04 or whatever, I just want to do the video, without it being inaccurate.

This probably isn't the best place, but as I said, the comment section only lead me to another way of saying "I don't know".

**Comment by dat810** [comment]
YouTube > YouTube Studio > Content > Click on a video you want to see > Analytics > On the graph, click See More > Hover on the graph to see data points.
That's it.

**Comment by PF94** [comment]
![image](https://user-images.githubusercontent.com/45898787/103930488-d4586980-50ec-11eb-8832-31bf12206bdc.png)
This does not work. The title of my issue says "How do I properly count the views of YouTube videos without it flutuating in the graph?", not "How do I check how manys views the video had in a day?".

If I paste this data, the bars will not grow gradually, instead, they will have a spasm because the data isn't the total views over time.

Post-late-2018 videos do seem to show "total views over time", however, that is unexportable, the only exportable thing regarding views is the "views of each day" thing that is unusable.

I did attempted making a "animated graph video", but I ended up making the data incomplete because I didn't wanted to bother calculating every single video's views overtime.

My oldest channel is 2.5k days old, and as I said, I have around 450-525 videos. I do not have the time of checking that amount of videos' views.

I did send a request to Abacada, but they seem to have given up on the "We will make an video about your channel's views overtime!" service, as they've only made 1 video and that was it.

**Comment by dat810** [comment]
Well then you will have to add each data point manually.

For example, to calculate the number of views on January 1, 2019 on a video that is published on January 1, 2018, you have to add all the previous data points before January 1, 2019, inclusive. That's a total of 366 data points.

Or if you have some calculus skills, it's a integral calculation.

**Comment by PF94** [comment]
I'm dropping this video idea entirely. Cary/Micheal seems to have forgot about their "We'll make a animated graph about your video's views" after 1 video, and it only serves as a shoutout. Ethier I do it manually for a video that no one will care about, or I will end up killing my YouTube channel because hundreds (or thousands) of logokids subscribed to my channel after they saw a video about my channel on Abacaba.

**Comment by PF94** [comment]
the confusion might have been caused by me not saying the word "cumulative", which is what i'm actually looking for.

**Comment by carykh** [comment]
You can just make the data cumulative using Google sheets' built-in features?
https://productivityspot.com/running-totals-google-sheets/

This tutorial's purpose isn't to provide users with every possible data-processing operation. A generally good idea is to get familiar with playing around with large datasets in general using Python, SQL, or any other programming language. Because then you can figure out how to do apply any operation you'd like!
